# Generated by Django 4.1.7 on 2023-03-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_name', models.EmailField(max_length=100)),
                ('phone_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
    ]
