# Generated by Django 4.1.7 on 2023-03-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_1', '0003_remove_coursestudent_exam_date_course_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='lab_1.teacher'),
        ),
    ]
