# Generated by Django 4.1.7 on 2023-03-19 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab_1', '0004_alter_student_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='exam_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
