# Generated by Django 4.1.7 on 2023-03-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_1', '0005_coursestudent_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher_content', to='lab_1.teacher'),
        ),
    ]
